name: flutter_clean_architecture_cubit_guide
description: "Guide: Authentication Flow (Login/Register/JWT) using Clean Architecture + Cubit/Provider"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  go_router: ^13.2.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^9.0.0
  

flutter:
 
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
